### ISSUE TITLE
ModuleNotFoundError: No module named 'look4bas.basis_format'

### ISSUE THREAD

**Issue by chrinide** [mfherbst/look4bas#14]
Hi all,

I just simply use **pip install look4bas** in WSL-Ubuntu/Python3.7.1

root@chrinide:/home/chrinide# look4bas --elements He Ne Ar

But I got below error:

Traceback (most recent call last):
  File "/home/chrinide/miniconda3/bin/look4bas", line 2, in <module>
    from look4bas.cli import main
  File "/home/chrinide/miniconda3/lib/python3.7/site-packages/look4bas/__init__.py", line 3, in <module>
    from . import emsl, ccrepo, elements, tlsutil
  File "/home/chrinide/miniconda3/lib/python3.7/site-packages/look4bas/emsl.py", line 6, in <module>
    from .basis_format import gaussian94
ModuleNotFoundError: No module named 'look4bas.basis_format'

**Comment by mfherbst** [comment]
Hi @chrinide thanks for the report. I can reproduce the issue ... working on a fix.

**Comment by mfherbst** [comment]
Newest version (0.3.1) with the fix is now on pypi, installable via `pip install -U look4bas`.
